# name = "Buddha Saru Magar" 
# age = 21
# address = "Kathmandu, Nepal"

# print(f"My name is {name}, I am {age} years old and I live in {address}.")


# DataTypes

# name = "Buddha Saru Magar" # String
# age = 21 # Integer
# height = 5.8 # Float
# is_student = True # Boolean

# using prompt to get user input
name = input("Enter your Name:")
age = int(input("Enter your age:"))

print(f"Hello !! {name}")
print("Happy Birthday..")
print(f"You are {age} years old now.")
