# name = "Buddha Saru Magar" 
# age = 21
# address = "Kathmandu, Nepal"

# print(f"My name is {name}, I am {age} years old and I live in {address}.")


# DataTypes

# name = "Buddha Saru Magar" # String
# age = 21 # Integer
# height = 5.8 # Float
# is_student = True # Boolean

# using prompt to get user input
# Budha


# 
name = input("Enter your name: ")

# result = len(name)

# find is used to find the index of the letter
# result = name.find("u")
# result = name.rfind("d")

# capitalize is used to Make the first letter To Upper case
# result = name.capitalize() 

# result = name.upper()
# result = name.lower()

# isdigit returns true if the sting is only digit otherwise false
# result = name.isdigit() 

# isalpha returns true if the string is alphabetic otherwise false
# result = name.isalpha()

# count
# result = name.count("d")

# replace
result = name.replace("d"," ")

print(result)
